
#389
#easy

#You are given two strings s and t.

#String t is generated by random shuffling string s and then add one more letter at a random position.

#Return the letter that was added to t.

 

#Example 1:

#Input: s = "abcd", t = "abcde"
#Output: "e"
#Explanation: 'e' is the letter that was added.
#Example 2:

#Input: s = "", t = "y"
#Output: "y"


#my own solution using python3:

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for c in s:
            if c in t:
                t = t.replace(c, "", 1)
        return t
